/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsukses.Views;

import java.awt.Choice;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import projectsukses.Controllers.*; 

/**
 *
 * @author ACER NITRO
 */
public class MainUser extends javax.swing.JFrame {
    int xx,xy;
    /**
     * Creates new form MainUser
     */
    
    public MainUser() {
        initComponents();
    }

    public JFrame getjFrame1() {
        return jFrame1;
    }

    public void setjFrame1(JFrame jFrame1) {
        this.jFrame1 = jFrame1;
    }
    
    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JPanel getPanelMain() {
        return panelMain;
    }

    public void setPanelMain(JPanel panelMain) {
        this.panelMain = panelMain;
    }

    public JLabel getTlDashboard() {
        return tlDashboard;
    }

    public void setTlDashboard(JLabel tlDashboard) {
        this.tlDashboard = tlDashboard;
    }

    public JLabel getTlLogout() {
        return tlLogout;
    }

    public void setTlLogout(JLabel tlLogout) {
        this.tlLogout = tlLogout;
    }

    public JLabel getTlLogout1() {
        return tlLogout1;
    }

    public void setTlLogout1(JLabel tlLogout1) {
        this.tlLogout1 = tlLogout1;
    }

    public JLabel getTlMain() {
        return tlMain;
    }

    public void setTlMain(JLabel tlMain) {
        this.tlMain = tlMain;
    }

    public JLabel getTlMain1() {
        return tlMain1;
    }

    public void setTlMain1(JLabel tlMain1) {
        this.tlMain1 = tlMain1;
    }

    public JLabel getTlTabel() {
        return tlTabel;
    }

    public void setTlTabel(JLabel tlTabel) {
        this.tlTabel = tlTabel;
    }

    public JLabel getTlTabel1() {
        return tlTabel1;
    }

    public void setTlTabel1(JLabel tlTabel1) {
        this.tlTabel1 = tlTabel1;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tlMain = new javax.swing.JLabel();
        tlDashboard = new javax.swing.JLabel();
        tlTabel = new javax.swing.JLabel();
        tlLogout = new javax.swing.JLabel();
        iconBack = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tlTabel1 = new javax.swing.JLabel();
        tlMain1 = new javax.swing.JLabel();
        tlLogout1 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabel User\n");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconAdminReal.png"))); // NOI18N
        jLabel2.setText("USER");

        tlMain.setBackground(new java.awt.Color(255, 255, 255));
        tlMain.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlMain.setForeground(new java.awt.Color(255, 255, 255));
        tlMain.setText("Personality");
        tlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlMainMouseClicked(evt);
            }
        });

        tlDashboard.setBackground(new java.awt.Color(255, 255, 255));
        tlDashboard.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlDashboard.setForeground(new java.awt.Color(255, 255, 255));
        tlDashboard.setText("Dashboard");
        tlDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlDashboardMouseClicked(evt);
            }
        });

        tlTabel.setBackground(new java.awt.Color(255, 255, 255));
        tlTabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlTabel.setForeground(new java.awt.Color(255, 255, 255));
        tlTabel.setText("Tabel User");
        tlTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlTabelMouseClicked(evt);
            }
        });

        tlLogout.setBackground(new java.awt.Color(255, 255, 255));
        tlLogout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlLogout.setForeground(new java.awt.Color(255, 255, 255));
        tlLogout.setText("Logout");
        tlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlLogoutMouseClicked(evt);
            }
        });

        iconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconBack.Realpng.png"))); // NOI18N
        iconBack.setText("jLabel7");
        iconBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tlLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(iconBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iconBack))
                .addGap(68, 68, 68)
                .addComponent(tlDashboard)
                .addGap(59, 59, 59)
                .addComponent(tlMain)
                .addGap(53, 53, 53)
                .addComponent(tlTabel)
                .addGap(51, 51, 51)
                .addComponent(tlLogout)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Finance");

        tlTabel1.setBackground(new java.awt.Color(0, 0, 0));
        tlTabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlTabel1.setText("Table User");
        tlTabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlTabel1MouseClicked(evt);
            }
        });

        tlMain1.setBackground(new java.awt.Color(0, 0, 0));
        tlMain1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlMain1.setText("Personality");
        tlMain1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlMain1MouseClicked(evt);
            }
        });

        tlLogout1.setBackground(new java.awt.Color(0, 0, 0));
        tlLogout1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlLogout1.setText("Exit");
        tlLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlLogout1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(tlMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(tlTabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(tlLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlTabel1)
                    .addComponent(tlMain1)
                    .addComponent(tlLogout1))
                .addContainerGap())
        );

        panelMain.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Halo Semuaaa, Kenalin Saya Admin");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlLogoutMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar dari Program?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        // Jika pengguna mengklik "Yes"
        if (response == JOptionPane.YES_OPTION) {
            // Tampilkan pesan "Kembali ke Menu Login"
            JOptionPane.showMessageDialog(null, "Kembali ke Menu Login", "Logout", JOptionPane.INFORMATION_MESSAGE);

            // Mengarahkan kembali ke halaman login
            LoginController lc = new LoginController();
            lc.showViewLoginUser(); 

            // Menutup jendela saat ini
            this.dispose();
        }
    }//GEN-LAST:event_tlLogoutMouseClicked

    private void tlTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlTabelMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(new TabelData());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_tlTabelMouseClicked

    private void tlDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlDashboardMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(new DUser());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_tlDashboardMouseClicked

    private void tlMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlMainMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(new RincianUser());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_tlMainMouseClicked

    private void tlLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlLogout1MouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar dari Program?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        // Jika pengguna mengklik "Yes", maka keluar dari program
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            // Jika pengguna mengklik "No", tetap di dalam program
            this.setVisible(true);
        }
       
    }//GEN-LAST:event_tlLogout1MouseClicked

    private void tlMain1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlMain1MouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(new RincianUser());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_tlMain1MouseClicked

    private void tlTabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlTabel1MouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(new TabelData());
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_tlTabel1MouseClicked

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void iconBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBackMouseClicked
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar dari Program?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        // Jika pengguna mengklik "Yes"
        if (response == JOptionPane.YES_OPTION) {
            // Tampilkan pesan "Kembali ke Menu Login"
            JOptionPane.showMessageDialog(null, "Kembali ke Menu Login", "Logout", JOptionPane.INFORMATION_MESSAGE);

            // Mengarahkan kembali ke halaman login
            LoginController lc = new LoginController();
            lc.showViewLoginUser(); 

            // Menutup jendela saat ini
            this.dispose();
        }
    }//GEN-LAST:event_iconBackMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconBack;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelMain;
    private javax.swing.JLabel tlDashboard;
    private javax.swing.JLabel tlLogout;
    private javax.swing.JLabel tlLogout1;
    private javax.swing.JLabel tlMain;
    private javax.swing.JLabel tlMain1;
    private javax.swing.JLabel tlTabel;
    private javax.swing.JLabel tlTabel1;
    // End of variables declaration//GEN-END:variables

    
}
