/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsukses.Views;


import java.awt.Choice;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import projectsukses.Controllers.*;
import projectsukses.Views.*;
/**
 *
 * @author ACER NITRO
 */
public class MainAdmin extends javax.swing.JFrame {
// DI sebelah tulisan Hello, welcomeLabel = new JLabel("Selamat Datang! (" + userName + ")");
    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
    }

    public JPanel getPanelAdmin() {
        return panelAdmin;
    }

    public void setPanelAdmin(JPanel PanelAdmin) {
        this.panelAdmin = PanelAdmin;
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public void setBtnLogin(JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    public JLabel getIconBack() {
        return iconBack;
    }

    public void setIconBack(JLabel iconBack) {
        this.iconBack = iconBack;
    }

    public JLabel gettDashboard() {
        return tDashboard;
    }

    public void settDashboard(JLabel tDashboard) {
        this.tDashboard = tDashboard;
    }

    public JLabel gettExit() {
        return tExit;
    }

    public void settExit(JLabel tExit) {
        this.tExit = tExit;
    }

    public JLabel gettLogout() {
        return tLogout;
    }

    public void settLogout(JLabel tLogout) {
        this.tLogout = tLogout;
    }

    public JLabel gettTabel() {
        return tTabel;
    }

    public void settTabel(JLabel tTabel) {
        this.tTabel = tTabel;
    }

    public JLabel gettTabel1() {
        return tTabel1;
    }

    public void settTabel1(JLabel tTabel1) {
        this.tTabel1 = tTabel1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tDashboard = new javax.swing.JLabel();
        tTabel = new javax.swing.JLabel();
        tLogout = new javax.swing.JLabel();
        iconBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tTabel1 = new javax.swing.JLabel();
        tExit = new javax.swing.JLabel();
        panelAdmin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Finance");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconAdminReal.png"))); // NOI18N
        jLabel2.setText("ADMIN");

        tDashboard.setBackground(new java.awt.Color(255, 255, 255));
        tDashboard.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tDashboard.setForeground(new java.awt.Color(255, 255, 255));
        tDashboard.setText("Dashboard");
        tDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDashboardMouseClicked(evt);
            }
        });

        tTabel.setBackground(new java.awt.Color(255, 255, 255));
        tTabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tTabel.setForeground(new java.awt.Color(255, 255, 255));
        tTabel.setText("Tabel");
        tTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTabelMouseClicked(evt);
            }
        });

        tLogout.setBackground(new java.awt.Color(255, 255, 255));
        tLogout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tLogout.setForeground(new java.awt.Color(255, 255, 255));
        tLogout.setText("Logout");
        tLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLogoutMouseClicked(evt);
            }
        });

        iconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconBack.Realpng.png"))); // NOI18N
        iconBack.setText("jLabel7");
        iconBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iconBack))
                .addGap(67, 67, 67)
                .addComponent(tDashboard)
                .addGap(70, 70, 70)
                .addComponent(tTabel)
                .addGap(68, 68, 68)
                .addComponent(tLogout)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Finance");

        tTabel1.setBackground(new java.awt.Color(255, 255, 255));
        tTabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tTabel1.setText("Tabel");
        tTabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTabel1MouseClicked(evt);
            }
        });

        tExit.setBackground(new java.awt.Color(255, 255, 255));
        tExit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tExit.setText("Exit");
        tExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addGap(176, 176, 176)
                .addComponent(tTabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(tExit)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tTabel1)
                    .addComponent(tExit))
                .addGap(24, 24, 24))
        );

        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        panelAdmin.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Halo Semuaaa, Kenalin Saya Admin");
        panelAdmin.add(jLabel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDashboardMouseClicked
        // TODO add your handling code here:
        panelAdmin.removeAll();
        panelAdmin.add(new DAdmin());
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_tDashboardMouseClicked

    private void tTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTabelMouseClicked
        // TODO add your handling code here:
       panelAdmin.removeAll();
        panelAdmin.add(new TabelUser());
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_tTabelMouseClicked

    private void tLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLogoutMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar dari Program?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        // Jika pengguna mengklik "Yes"
        if (response == JOptionPane.YES_OPTION) {
            // Tampilkan pesan "Kembali ke Menu Login"
            JOptionPane.showMessageDialog(null, "Kembali ke Menu Login", "Logout", JOptionPane.INFORMATION_MESSAGE);

            // Mengarahkan kembali ke halaman login
            LoginController lc = new LoginController();
            lc.showViewLoginAdmin(); 

            // Menutup jendela saat ini
            this.dispose();
        }
        
    }//GEN-LAST:event_tLogoutMouseClicked

    private void tTabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTabel1MouseClicked
        // TODO add your handling code here:
        panelAdmin.removeAll();
        panelAdmin.add(new TabelUser());
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_tTabel1MouseClicked

    private void tExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tExitMouseClicked
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar dari Program?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        // Jika pengguna mengklik "Yes", maka keluar dari program
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            // Jika pengguna mengklik "No", tetap di dalam program
            this.setVisible(true);
        }
    }//GEN-LAST:event_tExitMouseClicked

    private void iconBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBackMouseClicked
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar dari Program?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        // Jika pengguna mengklik "Yes"
        if (response == JOptionPane.YES_OPTION) {
            // Tampilkan pesan "Kembali ke Menu Login"
            JOptionPane.showMessageDialog(null, "Kembali ke Menu Login", "Logout", JOptionPane.INFORMATION_MESSAGE);

            // Mengarahkan kembali ke halaman login
            LoginController lc = new LoginController();
            lc.showViewLoginAdmin(); 

            // Menutup jendela saat ini
            this.dispose();
        }
       
        
        
    }//GEN-LAST:event_iconBackMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel iconBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JLabel tDashboard;
    private javax.swing.JLabel tExit;
    private javax.swing.JLabel tLogout;
    private javax.swing.JLabel tTabel;
    private javax.swing.JLabel tTabel1;
    // End of variables declaration//GEN-END:variables
}
