/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsukses.Views;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import projectsukses.Controllers.DataUserController;

/**
 *
 * @author ACER NITRO
 */
public class TabelUser extends javax.swing.JPanel {

    /**
     * Creates new form TabelUser
     */
    
    DataUserController duc; 
    public TabelUser() {
        initComponents();
        duc = new DataUserController(this);
        duc.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public JTable getTbUser() {
        return tbUser;
    }

    public void setTbUser(JTable tbUser) {
        this.tbUser = tbUser;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }


    public JTextField getTfInputKeterangan() {
        return tfInputKeterangan;
    }

    public void setTfInputKeterangan(JTextField tfInputKeterangan) {
        this.tfInputKeterangan = tfInputKeterangan;
    }
    
    public JTextField getTfInputCatatan() {
        return tfInputCatatan;
    }

    public void setTfInputCatatan(JTextField tfInputCatatan) {
        this.tfInputCatatan = tfInputCatatan;
    }

    public JTextField getTfInputHarga() {
        return tfInputHarga;
    }

    public void setTfInputHarga(JTextField tfInputHarga) {
        this.tfInputHarga = tfInputHarga;
    }

    public JTextField getTfInputKategori() {
        return tfInputKategori;
    }

    public void setTfInputKategori(JTextField tfInputKategori) {
        this.tfInputKategori = tfInputKategori;
    }

    public JTextField getTfInputNama() {
        return tfInputNama;
    }

    public void setTfInputNama(JTextField tfInputNama) {
        this.tfInputNama = tfInputNama;
    }

    public JFormattedTextField getTfInputTanggal() {
        return tfInputTanggal;
    }

    public void setTfInputTanggal(JFormattedTextField tfInputTanggal) {
        this.tfInputTanggal = tfInputTanggal;
    }

    public JTextField getTfInputId() {
        return tfInputId;
    }

    public void setTfInputId(JTextField tfInputId) {
        this.tfInputId = tfInputId;
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();
        tfInputId = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfInputCatatan = new javax.swing.JTextField();
        tfInputKategori = new javax.swing.JTextField();
        tfInputHarga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfInputNama = new javax.swing.JTextField();
        tfInputKeterangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfInputTanggal = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Keterangan", "Harga", "Tanggal", "Kategori", "Catatan"
            }
        ));
        tbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbUser);

        tfInputId.setEditable(false);
        tfInputId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfInputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputIdActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel9.setText("Input Kategori :");

        tfInputCatatan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfInputCatatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputCatatanActionPerformed(evt);
            }
        });

        tfInputKategori.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfInputKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputKategoriActionPerformed(evt);
            }
        });

        tfInputHarga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfInputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputHargaActionPerformed(evt);
            }
        });

        jLabel1.setText("Input Nama :");

        tfInputNama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfInputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputNamaActionPerformed(evt);
            }
        });

        tfInputKeterangan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfInputKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputKeteranganActionPerformed(evt);
            }
        });

        jLabel3.setText("Input Keterangan :");

        tfInputTanggal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfInputTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputTanggalActionPerformed(evt);
            }
        });

        jLabel8.setText("Input ID:");

        jLabel5.setText("Input Harga:");

        jLabel6.setText("Input Tanggal :");

        jLabel7.setText("Input Catatan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(tfInputNama)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(tfInputKategori)
                    .addComponent(tfInputHarga)
                    .addComponent(jLabel6)
                    .addComponent(tfInputCatatan)
                    .addComponent(tfInputTanggal)
                    .addComponent(tfInputKeterangan)
                    .addComponent(tfInputId, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(tfInputKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfInputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfInputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfInputKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfInputCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUserMouseClicked
        // TODO add your handling code here:

        // TODO add your handling code here:
        int baris = tbUser.getSelectedRow();
        tfInputId.setText(tbUser.getValueAt(baris, 0).toString());
        tfInputNama.setText(tbUser.getValueAt(baris, 1).toString());
        tfInputKeterangan.setText(tbUser.getValueAt(baris, 2).toString());
        tfInputHarga.setText(tbUser.getValueAt(baris, 3).toString());
        tfInputTanggal.setText(tbUser.getValueAt(baris, 4).toString());
        tfInputKategori.setText(tbUser.getValueAt(baris, 5).toString());
        tfInputCatatan.setText(tbUser.getValueAt(baris, 6).toString());

    }//GEN-LAST:event_tbUserMouseClicked

    private void tfInputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputIdActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        duc.delete();
        duc.isiTabel();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfInputCatatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputCatatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputCatatanActionPerformed

    private void tfInputKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputKategoriActionPerformed

    private void tfInputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputHargaActionPerformed

    private void tfInputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputNamaActionPerformed

    private void tfInputKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputKeteranganActionPerformed

    private void tfInputTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputTanggalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbUser;
    private javax.swing.JTextField tfInputCatatan;
    private javax.swing.JTextField tfInputHarga;
    private javax.swing.JTextField tfInputId;
    private javax.swing.JTextField tfInputKategori;
    private javax.swing.JTextField tfInputKeterangan;
    private javax.swing.JTextField tfInputNama;
    private javax.swing.JFormattedTextField tfInputTanggal;
    // End of variables declaration//GEN-END:variables
}
